---
title: SCEE
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: scee.ucsc@gmail.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: "/scee-jekyll"
url: http://scee.ucsc.edu
show_excerpts: true
minima:
  date_format: "%b %-d, %Y"
instagram_username: scee.ucsc
facebook_username: UCSC-Entrepreneurship-Club-381648289049770
linkedin_username: scee-student-creativity-and-entrepreneurial-empowerment
rss: rss
header_pages:
- index.html
- _pages/about.html
- _pages/blog.html
- _pages/contact.html
theme: minima
plugins:
- jekyll-feed
- jekyll-seo-tag
sass:
  sass_dir: _sass_imports
  style: compressed
include:
- _pages
