# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SCEE
timezone: America/Los_Angeles
email: scee.ucsc@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  SCEE aims to build a diverse community of student innovators and creative problem solvers. We encourage students, through our engaging events and workshops, to have unique insights on social and technical problems our society is facing today. We believe that innovation is the only way forward.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://scee.ucsc.edu" # the base hostname & protocol for your site, e.g. http://example.com

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# generate social links in footer
instagram_username: scee.ucsc
facebook_username: UCSC-Entrepreneurship-Club-381648289049770
linkedin_username: scee-student-creativity-and-entrepreneurial-empowerment

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- index.html
- _pages/about.html
- _pages/blog.html
- _pages/contact.html

# Build settings
theme: minima
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag

sass:
  sass_dir: _scss_imports
  style: compressed

include: ["_pages"]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
