---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: documents
  templates:
  - blog-post
- type: document
  path: _data/members.json
  label: Team Members
- type: directory
  path: _pages
  label: Pages
  create: documents
  match: "**/*"
  new_doc_ext: html
  templates:
  - html-page
- type: directory
  path: _data
  label: Data
  create: documents
  match: "**/*"
  new_doc_ext: json
- type: directory
  path: ''
  label: Everything
  create: all
  match: "**/*"
  new_doc_ext: scss
- type: directory
  path: assets/styles
  label: Assets
  create: all
  match: "**/*"
upload_dir: assets/images/post-images
public_path: "/assets/images/post-images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
